/*
 * Copyright 2020-2021 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.springframework.canal.config.endpoint;

import org.springframework.canal.listener.BatchMessageListener;
import org.springframework.canal.listener.EachMessageListener;
import org.springframework.canal.listener.MessageListener;
import org.springframework.canal.listener.adapter.BatchToEachAdapter;
import org.springframework.canal.listener.adapter.FilteringBatchMessageListenerAdapter;
import org.springframework.canal.listener.adapter.FilteringEachMessageListenerAdapter;
import org.springframework.canal.listener.adapter.MessageFilterStrategy;
import org.springframework.canal.support.converter.record.CanalMessageConverter;
import org.springframework.canal.support.converter.record.EachCanalMessageConverter;
import org.springframework.messaging.handler.annotation.support.MessageHandlerMethodFactory;
import org.springframework.messaging.handler.invocation.InvocableHandlerMethod;

import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.List;

/**
 * {@link CanalListenerEndpoint} POJO providing the methods to invoke to process
 * an incoming message for this endpoint.
 *
 * @param <T> the payload type.
 * @author 橙子
 * @since 2020/11/14
 */
public class CanalListenerClassEndpoint<T> extends AbstractCanalListenerEndpoint {
    private Object bean;
    private Method defaultMethod;
    private List<Method> handlerMethods;

    public CanalListenerClassEndpoint(List<Method> handlerMethods, Method defaultMethod, Object bean) {
        this.handlerMethods = handlerMethods;
        this.defaultMethod = defaultMethod;
        this.bean = bean;
    }

    public Object getBean() {
        return this.bean;
    }

    /**
     * Set the object instance that should manage this endpoint.
     *
     * @param bean the target bean instance.
     */
    public void setBean(Object bean) {
        this.bean = bean;
    }

    public Method getDefaultMethod() {
        return this.defaultMethod;
    }

    /**
     * Set the method to consume the message handled by method {@link InvocableHandlerMethod}
     * generated by the {@link MessageHandlerMethodFactory}.
     *
     * @param defaultMethod the target method for the {@link #bean}.
     * @see #setMessageHandlerMethodFactory(MessageHandlerMethodFactory)
     */
    public void setDefaultMethod(Method defaultMethod) {
        this.defaultMethod = defaultMethod;
    }

    public List<Method> getHandlerMethods() {
        return this.handlerMethods;
    }

    public void setHandlerMethods(List<Method> handlerMethods) {
        this.handlerMethods = handlerMethods;
    }

    @Override
    public MessageListener<?> createMessageListener(CanalMessageConverter messageConverter, BatchToEachAdapter<?> batchToEachAdapter, MessageFilterStrategy<?> filterStrategy) {
        InvocableHandlerMethod defaultInvocableMethod = this.defaultMethod == null ?
                null : getMessageHandlerMethodFactory().createInvocableHandlerMethod(this.bean, this.defaultMethod);
        final List<InvocableHandlerMethod> otherMethods = new ArrayList<>(this.handlerMethods.size());
        for (Method handlerMethod : this.handlerMethods)
            otherMethods.add(getMessageHandlerMethodFactory().createInvocableHandlerMethod(this.bean, handlerMethod));
        if (Boolean.TRUE.equals(getBatchListener())) {
            final BatchMessageListener<T> batchMessageListener = createBatchMessageListener(defaultInvocableMethod, otherMethods,
                    getErrorHandler(), messageConverter, (BatchToEachAdapter<T>) batchToEachAdapter);
            if (filterStrategy == null)
                return batchMessageListener;
            return new FilteringBatchMessageListenerAdapter<>(batchMessageListener, (MessageFilterStrategy<T>) filterStrategy);
        }
        final EachMessageListener<T> eachMessageListener = createEachMessageListener(defaultInvocableMethod, otherMethods,
                getErrorHandler(),
                messageConverter instanceof EachCanalMessageConverter ? (EachCanalMessageConverter<T>) messageConverter : null);
        if (filterStrategy == null)
            return eachMessageListener;
        return new FilteringEachMessageListenerAdapter<>(eachMessageListener, (MessageFilterStrategy<T>) filterStrategy);
    }
}
